# tools/New-ShowTreeTestData.ps1

param(
    [string]$Root = $null,

# Required when reusing an existing directory that was not previously
# created by this script.
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$markerFileName = '.showtree-testdata'

function Resolve-SafeTestDataRoot {
    param(
        [string]$RequestedRoot
    )

    if ([string]::IsNullOrWhiteSpace($RequestedRoot)) {
        $RequestedRoot = if ($IsWindows) {
            Join-Path (Join-Path $PSScriptRoot '..') 'TestFixtures'
        }
        else {
            '/tmp/show-tree/testfixtures'
        }
    }

    $basePath = (Get-Location).ProviderPath
    $fullPath = if ([System.IO.Path]::IsPathRooted($RequestedRoot)) {
        [System.IO.Path]::GetFullPath($RequestedRoot)
    }
    else {
        [System.IO.Path]::GetFullPath(
                [System.IO.Path]::Combine($basePath, $RequestedRoot)
        )
    }

    $pathRoot = [System.IO.Path]::GetPathRoot($fullPath)

    $dangerousPaths = @(
        [System.IO.Path]::GetFullPath($pathRoot),
        [System.IO.Path]::GetFullPath($basePath),
        [System.IO.Path]::GetFullPath($PSScriptRoot)
    )

    if ($HOME) {
        $dangerousPaths += [System.IO.Path]::GetFullPath($HOME)
    }

    foreach ($dangerousPath in $dangerousPaths) {
        if (-not $dangerousPath) {
            continue
        }

        $normalizedFullPath = $fullPath.TrimEnd(
                [System.IO.Path]::DirectorySeparatorChar,
                [System.IO.Path]::AltDirectorySeparatorChar
        )

        $normalizedDangerousPath = $dangerousPath.TrimEnd(
                [System.IO.Path]::DirectorySeparatorChar,
                [System.IO.Path]::AltDirectorySeparatorChar
        )

        if ($normalizedFullPath -eq $normalizedDangerousPath) {
            throw "Refusing to use unsafe test-data root: '$fullPath'"
        }
    }

    return $fullPath
}

function Reset-TestDataRoot {
    param(
        [string]$Path,
        [switch]$Force
    )

    if ([string]::IsNullOrWhiteSpace($Path)) {
        throw "Refusing to reset an empty test-data root."
    }

    $markerPath = Join-Path $Path $markerFileName

    if (Test-Path -LiteralPath $Path) {
        if (-not (Test-Path -LiteralPath $markerPath) -and -not $Force) {
            throw @"
Refusing to reset '$Path' because it was not created by this script.

To use this directory anyway, rerun with -Force:
  ./tools/New-ShowTreeTestData.ps1 -Root '$Path' -Force
"@
        }

        try {
            Get-ChildItem -LiteralPath $Path -Force |
                    Remove-Item -Recurse -Force -ErrorAction Stop
        }
        catch {
            if (-not $IsWindows) {
                $resolvedPath = try {
                    (Resolve-Path -LiteralPath $Path -ErrorAction Stop).Path
                }
                catch {
                    $Path
                }

                throw @"
Unable to clean the existing test-data directory:

  $resolvedPath

This can happen on Linux/macOS when generated fixtures include special
permission bits such as setuid, setgid, sticky directories, or read-only
permission mappings.

Please remove it manually and rerun the script:

  sudo rm -rf '$resolvedPath'

Original error:
  $($_.Exception.Message)
"@
            }

            throw
        }
    }
    else {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }

    New-Item `
        -ItemType File `
        -Path $markerPath `
        -Value "Generated by tools/New-ShowTreeTestData.ps1" `
        -Force |
            Out-Null
}

function Write-TextFile {
    param(
        [string]$Path,
        [string[]]$Content
    )

    $parent = Split-Path -Parent $Path
    if ($parent -and -not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }

    Set-Content -LiteralPath $Path -Value $Content -NoNewline:$false
}

function Set-AttributesPortable {
    param(
        [string]$Path,
        [System.IO.FileAttributes]$Attributes
    )

    try {
        $existing = [System.IO.File]::GetAttributes($Path)
        $preserve = [System.IO.FileAttributes]::Directory -bor [System.IO.FileAttributes]::ReparsePoint
        $newValue = ($existing -band $preserve) -bor $Attributes

        [System.IO.File]::SetAttributes($Path, $newValue)

        $final = [System.IO.File]::GetAttributes($Path)

        [pscustomobject]@{
            Applied         = $true
            Requested       = $Attributes.ToString()
            FinalAttributes = $final.ToString()
        }
    }
    catch {
        try {
            $final = [System.IO.File]::GetAttributes($Path)
            $finalText = $final.ToString()
        }
        catch {
            $finalText = $null
        }

        [pscustomobject]@{
            Applied         = $false
            Requested       = $Attributes.ToString()
            FinalAttributes = $finalText
        }
    }
}

function Set-FileTimes {
    param(
        [string]$Path,
        [datetime]$When
    )

    try {
        $item = Get-Item -LiteralPath $Path -Force
        $item.CreationTime   = $When
        $item.LastWriteTime  = $When
        $item.LastAccessTime = $When
        return $true
    }
    catch {
        return $false
    }
}

function Invoke-Chmod {
    param(
        [string]$Mode,
        [string]$Path
    )

    if ($IsWindows) {
        return $false
    }

    try {
        & chmod $Mode -- $Path
        return $LASTEXITCODE -eq 0
    }
    catch {
        return $false
    }
}

function New-Metadata {
    param(
        [string]$ItemPath,
        [hashtable]$Data,
        [string]$RootPath
    )

    $ordered = [ordered]@{}
    foreach ($k in ($Data.Keys | Sort-Object)) {
        $ordered[$k] = $Data[$k]
    }

    $relativeItemPath = try {
        [System.IO.Path]::GetRelativePath($RootPath, $ItemPath)
    }
    catch {
        $ItemPath
    }

    $record = [ordered]@{
        itemPath         = $ItemPath
        relativeItemPath = $relativeItemPath
        metadata         = $ordered
    }

    $script:metadataIndex.Add([pscustomobject]$record)
}

function New-FixtureDirectory {
    param(
        [string]$Parent,
        [string]$Name
    )

    $dir = Join-Path $Parent $Name
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
    return $dir
}

function Add-LinkMetadata {
    param(
        [string]$LinkPath,
        [string]$LinkType,
        [string]$Target,
        [bool]$Applied
    )

    New-Metadata -ItemPath $LinkPath -RootPath $rootFull -Data @{
        type     = "link"
        linkType = $LinkType
        target   = $Target
        applied  = $Applied
        platform = $PSVersionTable.Platform
    }
}

function New-LinkFixture {
    param(
        [ValidateSet('SymbolicLink', 'HardLink', 'Junction')]
        [string]$LinkType,

        [string]$Path,
        [string]$Target
    )

    try {
        New-Item -ItemType $LinkType -Path $Path -Target $Target -Force | Out-Null
        return $true
    }
    catch {
        return $false
    }
}

$Root = Resolve-SafeTestDataRoot -RequestedRoot $Root
Reset-TestDataRoot -Path $Root -Force:$Force

$rootFull = (Resolve-Path -LiteralPath $Root).Path

$dirsRoot    = Join-Path $rootFull "Directories"
$filesRoot   = Join-Path $rootFull "Files"
$linksRoot   = Join-Path $rootFull "Links"
$specialRoot = Join-Path $rootFull "SpecialPermissions"

$metadataIndex = [System.Collections.Generic.List[object]]::new()

New-Item -ItemType Directory -Path $dirsRoot, $filesRoot, $linksRoot -Force | Out-Null

# -----------------------
# Directories
# -----------------------

$dirCases = @(
    @{
        Name = "normal-dir"
        RequestedAttr = [IO.FileAttributes]::Normal
        AddInfoFile = $false
    }
    @{
        Name = $IsWindows ? "hidden-dir" : ".hidden-dir"
        RequestedAttr = [IO.FileAttributes]::Hidden
        AddInfoFile = $false
    }
    @{
        Name = "readonly-dir"
        RequestedAttr = [IO.FileAttributes]::ReadOnly
        AddInfoFile = $false
    }
    @{
        Name = "system-dir"
        RequestedAttr = [IO.FileAttributes]::System
        AddInfoFile = $false
        WindowsOnly = $true
    }
    @{
        Name = "readonly-system-dir"
        RequestedAttr = [IO.FileAttributes]::ReadOnly -bor [IO.FileAttributes]::System
        AddInfoFile = $false
        WindowsOnly = $true
    }
    @{
        Name = $IsWindows ? "hidden-readonly-dir" : ".hidden-readonly-dir"
        RequestedAttr = [IO.FileAttributes]::Hidden -bor [IO.FileAttributes]::ReadOnly
        AddInfoFile = $false
    }
    @{
        Name = $IsWindows ? "hidden-system-dir" : ".hidden-system-dir"
        RequestedAttr = [IO.FileAttributes]::Hidden -bor [IO.FileAttributes]::System
        AddInfoFile = $false
        WindowsOnly = $true
    }
    @{
        Name = $IsWindows ? "hidden-system-readonly-dir" : ".hidden-system-readonly-dir"
        RequestedAttr = [IO.FileAttributes]::Hidden -bor [IO.FileAttributes]::System -bor [IO.FileAttributes]::ReadOnly
        AddInfoFile = $false
        WindowsOnly = $true
    }
    @{
        Name = "nested-dir"
        RequestedAttr = [IO.FileAttributes]::Normal
        AddInfoFile = $false
    }
)

foreach ($case in $dirCases) {
    if ($case.WindowsOnly -band -not $IsWindows) { continue }
    
    $dir = New-FixtureDirectory -Parent $dirsRoot -Name $case.Name

    if ($case.Name -eq "nested-dir") {
        $nestedLeafDir = Join-Path (Join-Path (Join-Path $dir "a") "b") "c"
        New-Item -ItemType Directory -Path $nestedLeafDir -Force | Out-Null
        Write-TextFile -Path (Join-Path $nestedLeafDir "leaf.txt") -Content @("deep file")
    }
    elseif ($case.AddInfoFile) {
        Write-TextFile -Path (Join-Path $dir "info.txt") -Content @("directory fixture: $($case.Name)")
    }

    $attrResult = Set-AttributesPortable -Path $dir -Attributes $case.RequestedAttr

    New-Metadata -ItemPath $dir -RootPath $rootFull -Data @{
        type                 = "directory"
        case                 = $case.Name
        requestedWindowsAttr = $case.RequestedAttr.ToString()
        windowsAttrApplied   = $attrResult.Applied
        appliedWindowsAttr   = $attrResult.FinalAttributes
        platform             = $PSVersionTable.Platform
    }
}

# -----------------------
# Files
# -----------------------

$fileCases = @(
    @{
        Name = "normal.txt"
        Content = @("normal file")
        RequestedAttr = [IO.FileAttributes]::Normal
        Empty = $false
        Executable = $false
    }
    @{
        Name = "archive.txt"
        Content = @("archive file")
        RequestedAttr = [IO.FileAttributes]::Archive
        Empty = $false
        Executable = $false
        WindowsOnly = $true
    }
    @{
        Name = "executable.ps1"
        Content = @("Write-Output 'Hello, world!'")
        RequestedAttr = [IO.FileAttributes]::Normal
        Empty = $false
        Executable = $true
        UnixOnly = $true
    }
    @{
        Name = $IsWindows ? "hidden.txt" : ".hidden.txt"
        Content = @("hidden file")
        RequestedAttr = [IO.FileAttributes]::Hidden
        Empty = $false
        Executable = $false
    }
    @{
        Name = "readonly.txt"
        Content = @("readonly file")
        RequestedAttr = [IO.FileAttributes]::ReadOnly
        Empty = $false
        Executable = $false
    }
    @{
        Name = "system.txt"
        Content = @("system file")
        RequestedAttr = [IO.FileAttributes]::System
        Empty = $false
        Executable = $false
        WindowsOnly = $true
    }
    @{
        Name = $IsWindows ? "hidden-system.txt" : ".hidden-system.txt"
        Content = @("hidden system file")
        RequestedAttr = [IO.FileAttributes]::Hidden -bor [IO.FileAttributes]::System
        Empty = $false
        Executable = $false
        WindowsOnly = $true
    }
    @{
        Name = $IsWindows ? "hidden-readonly.txt" : ".hidden-readonly.txt"
        Content = @("hidden readonly file")
        RequestedAttr = [IO.FileAttributes]::Hidden -bor [IO.FileAttributes]::ReadOnly
        Empty = $false
        Executable = $false
    }
    @{
        Name = "readonly-system.txt"
        Content = @("readonly system file")
        RequestedAttr = [IO.FileAttributes]::ReadOnly -bor [IO.FileAttributes]::System
        Empty = $false
        Executable = $false
        WindowsOnly = $true
    }
    @{
        Name = $IsWindows ? "hidden-system-readonly.txt" : ".hidden-system-readonly.txt"
        Content = @("hidden system readonly file")
        RequestedAttr = [IO.FileAttributes]::Hidden -bor [IO.FileAttributes]::System -bor [IO.FileAttributes]::ReadOnly
        Empty = $false
        Executable = $false
        WindowsOnly = $true
    }
)

foreach ($case in $fileCases) {
    if ($case.WindowsOnly -band -not $IsWindows) { continue }
    if ($case.UnixOnly -band $IsWindows) { continue }
    
    $path = Join-Path $filesRoot $case.Name

    if ($case.Empty) {
        New-Item -ItemType File -Path $path -Force | Out-Null
    }
    else {
        Write-TextFile -Path $path -Content $case.Content
    }

    $execApplied = $false
    if ($case.Executable) {
        $execApplied = Invoke-Chmod -Mode '+x' -Path $path
    }

    $attrResult = Set-AttributesPortable -Path $path -Attributes $case.RequestedAttr
    $timeApplied = Set-FileTimes -Path $path -When ([datetime]"2024-01-01T01:01:01")

    New-Metadata -ItemPath $path -RootPath $rootFull -Data @{
        type                 = "file"
        fileName             = $case.Name
        requestedWindowsAttr = $case.RequestedAttr.ToString()
        windowsAttrApplied   = $attrResult.Applied
        appliedWindowsAttr   = $attrResult.FinalAttributes
        requestedExecutable  = $case.Executable
        appliedExecutable    = $execApplied
        requestedEmpty       = $case.Empty
        appliedTimestamp     = $timeApplied
        platform             = $PSVersionTable.Platform
    }
}

# -----------------------
# Links
# -----------------------

$linkTargetFile = Join-Path $filesRoot "normal.txt"
$linkTargetDir  = Join-Path $dirsRoot "normal-dir"

$fileSymlinkPath = Join-Path $linksRoot "file-to-normal.symlink"
$ok = New-LinkFixture -LinkType SymbolicLink -Path $fileSymlinkPath -Target $linkTargetFile
Add-LinkMetadata -LinkPath $fileSymlinkPath -LinkType "SymbolicLink" -Target $linkTargetFile -Applied $ok

$dirSymlinkPath = Join-Path $linksRoot "dir-to-normal.symlink"
$ok = New-LinkFixture -LinkType SymbolicLink -Path $dirSymlinkPath -Target $linkTargetDir
Add-LinkMetadata -LinkPath $dirSymlinkPath -LinkType "SymbolicLink" -Target $linkTargetDir -Applied $ok

$hardlinkPath = Join-Path $linksRoot "hardlink-to-normal.txt"
$ok = New-LinkFixture -LinkType HardLink -Path $hardlinkPath -Target $linkTargetFile
Add-LinkMetadata -LinkPath $hardlinkPath -LinkType "HardLink" -Target $linkTargetFile -Applied $ok

$missingTarget = Join-Path $rootFull "does-not-exist.txt"
$brokenSymlinkPath = Join-Path $linksRoot "broken-to-missing.symlink"
$ok = New-LinkFixture -LinkType SymbolicLink -Path $brokenSymlinkPath -Target $missingTarget
Add-LinkMetadata -LinkPath $brokenSymlinkPath -LinkType "BrokenSymbolicLink" -Target $missingTarget -Applied $ok

if ($IsWindows) {
    $junctionPath = Join-Path $linksRoot "junction-to-normal-dir"
    $ok = New-LinkFixture -LinkType Junction -Path $junctionPath -Target $linkTargetDir
    Add-LinkMetadata -LinkPath $junctionPath -LinkType "Junction" -Target $linkTargetDir -Applied $ok
}

# -----------------------
# Unix special permissions
# -----------------------

if (-not $IsWindows) {
    New-Item -ItemType Directory -Path $specialRoot -Force | Out-Null

    $specialCases = @(
        @{
            Name = "setuid-file"
            Type = "File"
            Content = "setuid test"
            Chmod = "4755"
            State = "SetUid"
        }
        @{
            Name = "setgid-file"
            Type = "File"
            Content = "setgid test"
            Chmod = "2755"
            State = "SetGid"
        }
        @{
            Name = "setuid-setgid-file"
            Type = "File"
            Content = "setuid and setgid test"
            Chmod = "6755"
            State = "SetUid+SetGid"
        }
        @{
            Name = "setgid-dir"
            Type = "Directory"
            Chmod = "2775"
            State = "SetGid"
        }
        @{
            Name = "sticky-dir"
            Type = "Directory"
            Chmod = "1777"
            State = "Sticky"
        }
        @{
            Name = "setgid-sticky-dir"
            Type = "Directory"
            Chmod = "3777"
            State = "SetGid+Sticky"
        }
    )

    foreach ($case in $specialCases) {
        $path = Join-Path $specialRoot $case.Name

        if ($case.Type -eq "Directory") {
            New-Item -ItemType Directory -Path $path -Force | Out-Null
        }
        else {
            Write-TextFile -Path $path -Content @($case.Content)
        }

        $chmodApplied = Invoke-Chmod -Mode $case.Chmod -Path $path

        New-Metadata -ItemPath $path -RootPath $rootFull -Data @{
            type          = "special-permission"
            fixtureType   = $case.Type
            case          = $case.Name
            expectedState = $case.State
            requestedMode = $case.Chmod
            chmodApplied  = $chmodApplied
            platform      = $PSVersionTable.Platform
        }
    }
}

# -----------------------
# Metadata index
# -----------------------

$metadataFile = Join-Path $rootFull "metadata-index.json"

$indexDocument = [ordered]@{
    schemaVersion = 1
    generatedAt   = (Get-Date).ToString("o")
    platform      = $PSVersionTable.Platform
    pwshVersion   = $PSVersionTable.PSVersion.ToString()
    root          = $rootFull
    fixtureCount  = $metadataIndex.Count
    fixtures      = $metadataIndex
}

$indexDocument |
        ConvertTo-Json -Depth 10 |
        Set-Content -LiteralPath $metadataFile -Encoding utf8

Write-Host "Created cross-platform fixtures under: $rootFull"

Get-ChildItem -LiteralPath $rootFull -Recurse -Force |
        Select-Object FullName, Attributes, LinkType, Length, LastWriteTime
